// LEETCODE PROBLEM NUMBER 50 - POW(X,N)


// APPROACH NUMBER - 1 THE MOST BRUTE FORCE APPROACH 
// IN THIS APPROACH WE WILL SIMPLY USE THE BUILT-IN FUNCTION PRESENT IN THE C++ - pow(a,b)
// ALTHOUGH IT WILL GIVE THE O(1) TIME AND SPACE COMPLEXITY BUT THIS IS NOT THE MOST OPTIMAL APPROACH FROM INTERVIEW PERSPECTIVE

class Solution {
public:
    double myPow(double x, int n) {
        return pow(x,n);
    }
};





//APPROACH NUMBER - 2 THE RECURSION + MATHS APPROACH 

